
services:

  postgres:
    image: postgres:16
    container_name: bicos-db
    restart: always

    environment:
      POSTGRES_DB: ${CHAVE_DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "${CHAVE_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
